config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'posts#index'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  title      :string
#  content    :text
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /comments or /comments.json
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

  # GET /comments/new
  def new
    return unless user_signed_in?

    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  # GET /comments/1/edit
  def edit
    return unless user_signed_in?

    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  # POST /comments or /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params.merge(user_id: current_user.id))
    return unless user_can_modify_comment?

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render 'posts/show', status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if user_can_modify_comment?
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to post_path(@post), notice: 'Comment was successfully updated.' }
          format.json { render :show, status: :ok, location: @comment }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, alert: 'You cant edit this comment'
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    if user_can_modify_comment?
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully deleted.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, notice: 'Cant destroy comment that arent your'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:title, :content)
  end

  def user_can_modify_comment?
    current_user.admin? || current_user.id == @comment.user.id
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p class="fs-4 fw-bold">
    <%= comment.title %>
  </p>
  <p class="fs-6">
    <%= comment.content %>
  </p>
  <p class="fs-6 fst-italic text-end mt-5">
    By: 
    <%= comment.user.email %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment], url: post_comments_path(@post)) do |form| %>
  <div class="d-flex flex-column">
    <div>
      <%= form.label :title, class: "d-block mb-2" %>
      <%= form.text_field :title, class:"w-100 p-2 rounded-2 border" %>
    </div>
    <div class="my-3">
      <%= form.label :content, class: "d-block mb-2" %>
      <%= form.text_area :content, class:"w-100 p-2 rounded-2", rows: 5 %>
    </div>
    <div class="mb-3">
      <%= form.submit "Update Comment", class: "btn btn-sm btn-outline-warning" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>
<div class="border rounded-4 p-3">
  <%= render "form", comment: @comment %>
  <div class="mt-3 d-flex gap-4">
    <%= link_to "Show more", post_comment_path(@post, @comment), class: "link-warning" %>
    <%= link_to "Back", post_comments_path(@post), class: "link-warning" %>
  </div>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Comments</h1>
<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", post_comment_path(@post, comment) %>
    </p>
  <% end %>
</div>
<% if user_signed_in? %>
  <%= link_to "New comment", new_post_comment_path(@post) %>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>
<%= render "form", comment: @comment %>
<br>
<div>
  <%= link_to "Back to comments", post_comments_path(@post) %>
</div>

app/views/comments/show.html.erb
<div class="border rounded-4 p-3">
  <%= render @comment %>
  <% if user_signed_in? && (@comment.user == current_user || current_user.admin?) %>
    <div class="d-flex gap-4 align-items-center justify-content-center">
      <%= link_to "Edit", edit_post_comment_path(@comment.post, @comment), class: "link-warning" %>
      <%= link_to "Back", post_comments_path(@comment.post), class: "link-warning" %>
      <%= button_to "Delete", post_comment_path(@comment.post, @comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
    </div>
  <% end %>
</div>