config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'posts#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string
#  content    :text
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if user_can_modify_post?
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: 'You Donnt Have Permission to edit this post'
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    if user_can_modify_post?
      @post.destroy

      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, alert: 'You Need Admin privileges to delete a post or be the author'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content)
  end

  # Metodo para saber si el usuario es admin o quien creo el post
  def user_can_modify_post?
    current_user.admin? || current_user.id == @post.user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div class="d-flex flex-column">
    <div>
      <%= form.label :title, class: "d-block mb-2" %>
      <%= form.text_field :title, class:"w-100 p-2 rounded-2 border" %>
    </div>
    <div class="my-3">
      <%= form.label :content, class: "d-block mb-2" %>
      <%= form.text_area :content, class:"w-100 p-2 rounded-2", rows: 10, cols: 30 %>
    </div>
    <div class="mb-3">
      <%= form.submit "Update", class: "btn btn-sm btn-outline-warning" %>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="fs-4 fw-bold">
    <%= post.title %>
  </p>
  <p class="fs-6">
    <%= simple_format(post.content) %>
  </p>
  <p class="fs-6 fst-italic text-end mt-5">
    By: 
    <%= post.user.email %>
  </p>
</div>

app/views/posts/edit.html.erb
<h3 class="display-5">Editing <%= @post.title %></h3>
<div class="border mt-3 rounded-4 p-3">
  <%= render "form", post: @post %>
  <div class="d-flex gap-4">
    <%= link_to "Show this post", @post, class:"link-warning" %>
    <%= link_to "Back to posts", posts_path, class:"link-warning" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="d-flex align-items-center justify-content-between mb-3">
  <h1 class="display-5 text-warning">News</h1>
  <% if user_signed_in? %>
    <%= link_to "Create a news", new_post_path, class: "btn btn-outline-warning btn-sm" %>
  <% end %>
</div>
<div id="posts">
  <% @posts.each do |post| %>
    <div class="mb-5 border p-3 rounded-4">
      <%= render post %>
      <p>
        <%= link_to "See more", post, class: "link-warning" %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div class="p-3 border rounded-4">
  <%= render @post %>
  <!-- Botones y links del post -->
  <% if user_signed_in? && (@comment.user == current_user || current_user.admin?) %>
    <div class="d-flex gap-4 align-items-center">
      <%= link_to "Edit this post", edit_post_path(@post), class:"link-warning m-0" %>
      <%= link_to "Back to posts", posts_path, class:"link-warning m-0" %>
      <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-sm btn-outline-danger mt-2" %>
    </div>
  <% end %>
</div>
<!-- Comentarios del post -->
<h2 class="my-5 display-6">Comments</h2>
<% @post.comments.each do |comment|%>
  <div class="border mb-4 p-3 rounded-4">
    <p class="fs-4"><%= comment.title %></p>
    <p><%= comment.content %></p>
    <% if user_signed_in? && (@comment.user == current_user || current_user.admin?) %>
      <div class="d-flex gap-3">
        <%= link_to "Edit", edit_post_comment_path(@post, comment), class: "link-warning" %>
        <%= link_to "Delete", post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "link-warning" %>
      </div>
    <% end %>
  </div>
<% end %>
<!-- Formulario de comentarios -->
<% if user_signed_in? %>
  <%= form_with(model: [ @post, @post.comments.build ], local: true, class:"border rounded-4 p-3 mw-100") do |form| %>
    <div class="d-flex flex-column">
      <div class="">
        <%= form.label :title, class: "d-block mb-2" %>
        <%= form.text_field :title, class:"w-100 p-2" %>
      </div>
      <div class="my-3">
        <%= form.label :content, class: "d-block mb-2" %>
        <%= form.text_area :content, class:"w-100 pb-3 px-2 pt-1", placeholder: "Leave a comment here" %>
      </div>
      <div>
        <%= form.submit "Add Comment", class: "btn btn-sm btn-outline-warning mt-3" %>
      </div>
    </div>
  <% end %>
<% end %>